identity-server:
  deployment:
    imagePullPolicy: IfNotPresent
    image:
      registry: "docker.wso2.com"
      repository: "wso2is"
      tag: "7.2.0"
    apparmor:
      enabled: false
    # Optional: Adjusting resources if the pod is being killed
    resources:
      requests:
        memory: "2Gi"
        cpu: "2000m"
      limits:
        memory: "4Gi"
        cpu: "3000m"