image:
  repository: "wso2/wso2is"
  tag: "7.2.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

# If the chart requires a sub-key, we provide that too:
identity-server:
  image:
    repository: "wso2/wso2is"
    tag: "7.2.0"
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  persistence:
    enabled: true
    storageClass: "local-path" 

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx  
    hosts:
      - host: wso2is.local
        paths:
          - /