# This name must match the 'name' in your dependencies list in Chart.yaml
identity-server:
  image:
    repository: "docker.wso2.com/wso2is"
    tag: "7.2.0"
    pullPolicy: IfNotPresent
  wso2:
    deployment:
      imagePullPolicy: IfNotPresent

  # Some versions use this
  image:
    repository: "wso2/wso2is"
    tag: "7.2.0"
    pullPolicy: IfNotPresent

  # Newer versions use this specific sub-key
  wso2is:
    image:
      repository: "wso2/wso2is"
      tag: "7.2.0"