identity-server:
  # The chart likely uses 'wso2is' as the internal key for the app components
  wso2is:
    image:
      repository: "wso2/wso2is"
      tag: "7.2.0"
      pullPolicy: IfNotPresent
  
  # Just in case it's at the root of the subchart
  image:
    repository: "wso2/wso2is"
    tag: "7.2.0"
    pullPolicy: IfNotPresent

  imagePullSecrets: []

  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"